from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/login/', views.admin_login, name='admin_login'),
    path('admin/register/', views.admin_registration, name='admin_registration'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('alumni/login/', views.alumni_login, name='alumni_login'),
    path('alumni/register/', views.alumni_registration, name='alumni_registration'),
    path('alumni/profile/', views.alumni_profile, name='alumni_profile'),
    path('alumni/edit-profile/', views.alumni_edit_profile, name='alumni_edit_profile'),
    path('alumni/share/<int:id>/', views.share_alumni_profile, name='share_alumni_profile'),
    path('alumni/forgot-password/', views.alumni_forgot_password, name='alumni_forgot_password'),
    path('alumni/reset-password/', views.alumni_reset_password, name='alumni_reset_password'),
    path('alumni_coordinator/login/', views.alumni_coordinator_login, name='alumni_coordinator_login'),
    path('alumni_coordinator/register/', views.alumni_coordinator_registration, name='alumni_coordinator_registration'),
    path('alumni_coordinator/dashboard/', views.alumni_coordinator_dashboard, name='alumni_coordinator_dashboard'),
    path('alumni_coordinator/edit-profile/', views.edit_coordinator_profile, name='edit_coordinator_profile'),
    path('alumni_coordinator/export/', views.export_alumni_to_excel, name='export_alumni_to_excel'),
    path('alumni/edit/<int:id>/', views.edit_alumni, name='edit_alumni'),
    path('alumni/delete/<int:id>/', views.delete_alumni, name='delete_alumni'),
    path('logout/', views.logout_view, name='logout'),
    path('gallery/', views.gallery, name='gallery'),
    path('admin/manage_gallery_photos/', views.manage_gallery_photos_admin, name='manage_gallery_photos_admin'),
    path('coordinator/manage_gallery_photos/', views.manage_gallery_photos_coordinator, name='manage_gallery_photos_coordinator'),
    path('add_gallery_photo/', views.add_gallery_photo, name='add_gallery_photo'),
    path('delete_gallery_photo/<int:id>/', views.delete_gallery_photo, name='delete_gallery_photo'),
    path('admin/manage_comments/', views.manage_comments_admin, name='manage_comments_admin'),
    path('coordinator/manage_comments/', views.manage_comments_coordinator, name='manage_comments_coordinator'),
    path('add_comment/', views.add_comment, name='add_comment'),
    path('delete_comment/<int:id>/', views.delete_comment, name='delete_comment'),
    path('edit_alumni_coordinator_profile/', views.edit_alumni_coordinator_profile, name='edit_alumni_coordinator_profile'),
    path('about/', views.about_us, name='about_us'),
    path('batch-mentor/login/', views.batch_mentor_login, name='batch_mentor_login'),
    path('batch-mentor/register/', views.batch_mentor_registration, name='batch_mentor_registration'),
    path('batch-mentor/dashboard/', views.batch_mentor_dashboard, name='batch_mentor_dashboard'),
    path('batch-mentor/view/', views.view_batch_mentors, name='view_batch_mentors'),
    path('batch-mentor/edit/<int:id>/', views.edit_batch_mentor, name='edit_batch_mentor'),
    path('batch-mentor/delete/<int:id>/', views.delete_batch_mentor, name='delete_batch_mentor'),
    path('batch-mentor/export/', views.export_batch_mentor_to_excel, name='export_batch_mentor_to_excel'),
    path('batch-mentor/assign-batch/', views.assign_batch_to_mentor, name='assign_batch_to_mentor'),
    path('batch-mentor/view-alumni/<int:mentor_id>/', views.view_alumni_in_batches, name='view_alumni_in_batches'),
    path('batch-mentor/available/', views.view_available_batch_mentors, name='view_available_batch_mentors'),
]