# Generated by Django 5.1.5 on 2025-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='batchmentor',
            name='assigned_batches',
            field=models.ManyToManyField(blank=True, related_name='mentors_assigned', to='alumni.graduationyear'),
        ),
    ]
