# Generated by Django 5.1.5 on 2025-02-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchmentor',
            name='assigned_batches',
        ),
        migrations.RemoveField(
            model_name='batchmentor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='batchmentor',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='BatchMentor',
        ),
    ]
