# Generated by Django 5.1.5 on 2025-01-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumni_is_active_alumni_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='is_staff',
        ),
    ]
