# Generated by Django 5.1.5 on 2025-04-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='media',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='notices/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='media',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='events/'),
        ),
    ]
