# Generated by Django 5.1.5 on 2025-04-04 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_notice_media_alter_event_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
